packages:
  - "apps/*"
  - "packages/*"

catalog:
  # Shared dependency versions
  typescript: ^5.7.0
  drizzle-orm: ^0.38.0
  drizzle-kit: ^0.30.0
  pg: ^8.13.0
  zod: ^3.24.0
  ai: ^4.0.0
  "@ai-sdk/anthropic": ^1.0.0
  "@ai-sdk/openai": ^1.0.0
